# Generated by Django 3.2.1 on 2021-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('starting_user', models.CharField(max_length=25)),
                ('ending_user', models.CharField(max_length=25)),
            ],
        ),
    ]
