# Generated by Django 3.2.1 on 2021-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='saltbae',
            field=models.CharField(default=11111, max_length=5),
            preserve_default=False,
        ),
    ]
