# Generated by Django 3.2.1 on 2021-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_session_saltbae'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='messages',
            field=models.TextField(default=22222),
            preserve_default=False,
        ),
    ]
