# Generated by Django 3.2.1 on 2021-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_session_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='count_message',
            field=models.IntegerField(default=0),
        ),
    ]
